version: '3.9'

services:
  back:
    build: .
    ports:
      - "8000:8000"
    container_name: cesizen-back
    env_file:
      - ./.env
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0
    container_name: cesizen-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cesizen
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
