version: '3.8'

services:
  db:
    image: mysql:8
    container_name: cesizen-db
    restart: always
    environment:
      MYSQL_DATABASE: cesizen
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - cesinet

  back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cesizen-back
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: cesizen
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    networks:
      - cesinet

volumes:
  mysql_data:

networks:
  cesinet:
