name: CD - Deploy Backend (Local)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Déploiement local Laravel + MySQL
    runs-on: self-hosted

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Copier le fichier .env
        run: cp .env.example .env

      - name: Lancer les conteneurs Docker
        run: docker compose up -d --build

      - name: Attendre MySQL
        run: sleep 15

      - name: Générer la clé Laravel
        run: docker exec cesizen-back php artisan key:generate

      - name: Lancer les migrations
        run: docker exec cesizen-back php artisan migrate --force

      - name: Lancer les seeders
        run: docker exec cesizen-back php artisan db:seed --force

      - name: Tester si Laravel répond
        run: |
          for i in {1..10}; do
            curl --silent http://localhost:8000 > /dev/null && break
            echo "Laravel pas encore prêt..."
            sleep 2
          done

      - name: Afficher les logs Laravel en cas d'erreur
        if: failure()
        run: docker exec cesizen-back cat storage/logs/laravel.log || echo "Aucun log Laravel trouvé"
