name: CD - Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploiement Laravel + MySQL (Docker)
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Docker
        uses: docker/setup-buildx-action@v3

      - name: Créer le fichier .env
        run: |
          cp .env.example .env

      - name: Construire et lancer les conteneurs
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Attendre que MySQL soit prêt
        run: |
          sleep 20

      - name: Migrer la base de données
        run: |
          docker exec cesizen-back php artisan migrate --force

      - name: Exécuter les seeders
        run: docker exec cesizen-back php artisan db:seed --force
      
      - name: Attendre que Laravel soit prêt
        run: |
            for i in {1..30}; do
              curl --silent http://localhost:8000 > /dev/null && break
              echo "Attente de Laravel..."
              sleep 2
            done

      - name: Tester Laravel depuis un conteneur
        run: |
          docker run --rm --network=cesinet curlimages/curl:latest curl --fail http://cesizen-back:8000

          
      - name: Afficher les logs Laravel après échec
        if: failure()
        run: docker exec cesizen-back cat storage/logs/laravel.log || echo "Pas de log Laravel"

