name: CI Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: cesizen
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Configurer PHP, Composer et extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo, pdo_mysql, mbstring

      - name: Créer le fichier .env
        run: |
          cp .env.example .env
          sed -i 's/DB_HOST=.*/DB_HOST=mysql/' .env
          php artisan key:generate

      - name: Installer les dépendances
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Attendre que MySQL soit prêt
        run: |
          for i in {1..15}; do
            if mysqladmin ping -h mysql -u laravel -plaravel --silent; then
              break
            fi
            echo "En attente de MySQL..."
            sleep 3
          done

      - name: Lancer les migrations avec seed
        run: php artisan migrate --seed
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: cesizen
          DB_USERNAME: laravel
          DB_PASSWORD: laravel

      - name: Lancer les tests (si tu en as)
        run: php artisan test || echo "Pas de tests définis"
