name: CI Laravel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: cesizen
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Configurer PHP, Composer et extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo, pdo_mysql, mbstring

      - name: Installer les dépendances
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Créer le fichier .env
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Attendre que MySQL soit prêt
        run: sleep 15

      - name: Lancer les migrations avec seed
        run: php artisan migrate --seed

      - name: Lancer les tests (si tu en as)
        run: php artisan test || echo "Pas de tests définis"
